core/views.py
from flask import Blueprint, render_template, redirect, request, url_for, flash, abort
from flask_login import login_required, login_user, logout_user, current_user
from .models import User, Transactions, Account
from .com import Utils
from .conf import FAKE_SLOW_PAGE, OVERLAY, QUICK_SIGN_OUT, SHOW_WELCOME, RANDOM_REFRESH, MAX_NUM_LENGTH 
from markdown2 import markdown_path
from random import choice
from core import db
from sqlalchemy import desc

views = Blueprint("views", __name__)

settings = {
    "fakeSlowPage": FAKE_SLOW_PAGE,
    "fakeOverlay": OVERLAY,
    "quickSignOut": QUICK_SIGN_OUT,
    "showWelcome": SHOW_WELCOME,
    "randomRefresh": RANDOM_REFRESH,
    "maxNumLength": MAX_NUM_LENGTH,
}

@views.route("/", methods=["GET", "POST"])
def index():
    slogan = choice(Utils.slogans)
    return render_template("index.html", slogan=slogan, settings=settings, user=current_user)

@views.route("/config/", methods=["GET", "POST"])
def config(): 
    if request.method == "POST":
        def addAccountAction(request):
            name = request.form["account_name"]
            balance = request.form["account_balance"]
            account_user_id = int(request.form["account_user_id"])
            validate = Utils.CommonFunctions.valAccountAction(name, balance)

            if "valid" in validate:
                account = Account(uid=Utils.CommonFunctions.genUid(), name=name, balance=balance, user_id=account_user_id)
                db.session.add(account)
                db.session.commit()
            
            elif "valid" not in validate and "flashed" in validate:
                flash(validate["flashed"], category="error")

            return redirect(url_for("views.config"))

        def addTransactionAction(request):
            name = request.form.get("transaction_name")
            amount = request.form.get("transaction_amount")
            transaction_type = request.form.get("transaction_type")
            transaction_account_id = request.form.get("transaction_account_id")
            validate = Utils.CommonFunctions.valTransactionAction(name, amount, transaction_type, transaction_account_id)

            if "valid" in validate:
                transaction = Transactions(uid=Utils.CommonFunctions.genUid(), name=name, amount=amount, transaction_type=transaction_type, account_id=transaction_account_id)
                db.session.add(transaction)
                db.session.commit()
            
            elif "valid" not in validate and "flashed" in validate:
                flash(validate["flashed"], category="error")

            return redirect(url_for("views.config"))

        def signUpAction(request):
            email = request.form["email"]
            name = request.form["name"]
            password1 = request.form["password1"]
            password2 = request.form["password2"]
            account_number = int(request.form["account_number"])
            routing_number = int(request.form["routing_number"])
            balance = request.form["balance"]
            validate = Utils.CommonFunctions.valSignup(email, name, password1, password2, account_number, routing_number)
            
            if "valid" in validate:
                user = User(uid=Utils.CommonFunctions.genUid(), email=email, name=name, password=password1, account_number=account_number, routing_number=routing_number, balance=balance)
                db.session.add(user)
                db.session.commit()

                login_user(user, remember=True)

                return redirect(url_for("views.index"))
            
            elif "valid" not in validate and "flashed" in validate:
                flash(validate['flashed'], category="error")
                return redirect(url_for("views.config"))

        if request.form.get("email", False) != False and request.form.get("name", False) != False and request.form.get("password1", False) != False and request.form.get("password2", False) != False and request.form.get("account_number", False) != False and request.form.get("routing_number", False) != False and request.form.get("balance", False):
            signUpAction(request)
        
        elif request.form.get("account_name", False) != False and request.form.get("account_balance", False) != False and request.form.get("account_user_id", False) != False:
            addAccountAction(request)
        
        elif request.form.get("transaction_name", False) != False and request.form.get("transaction_amount", False) != False and request.form.get("transaction_type", False) != False and request.form.get("transaction_account_id", False) != False:
            addTransactionAction(request)
        
        else:
            flash("No data", category="error")

        return redirect(url_for('views.config'))
    
    else:
        users = User.query.all()
        return render_template("config.html", settings=settings, user=current_user, users=users)

@views.route("/login/", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        email = request.form["email"]
        password = request.form["password"]
        
        validate = Utils.CommonFunctions.valLogin(email, password)

        if "valid" in validate:
            user = User.query.filter_by(email=email).first()
            login_user(user, remember=True)
            flash(validate["flashed"], category="success")

            return redirect(url_for('views.index'))
        
        elif "valid" not in validate and "flashed" in validate:
            flash(validate["flashed"], category="error")
            return redirect(url_for('views.login'))
    
    else:
        return render_template("login.html", settings=settings, user=current_user)

@views.route("/profile/")
@login_required
def profile():
    return redirect(url_for('views.select_account'))

@views.route("/profile/select_account/")
@login_required
def select_account():
    c_nums = Utils.CommonFunctions.genCensoredNumbers(current_user.account_number, current_user.routing_number)
    
    return render_template("profile/select_account.html", 
        settings=settings, 
        user=current_user, 
        balance="{:,}".format(float(current_user.balance)),
        account_number=c_nums["account_num"], 
        routing_number=c_nums["routing_num"],
        account_num_stars=c_nums["account_num_stars"],
        routing_num_stars=c_nums["routing_num_stars"]
    )

@views.route("/profile/account/<string:uid>/")
@login_required
def account(uid):
    account = Account.query.filter_by(uid=uid).first()

    if account == None:
        abort(404)

    account_transactions = Transactions.query.filter_by(account_id=account.id).order_by(Transactions.created.desc()).all()
    c_nums = Utils.CommonFunctions.genCensoredNumbers(current_user.account_number, current_user.routing_number)

    return render_template("profile/account.html", 
        settings=settings, 
        user=current_user, 
        balance="{:,}".format(float(current_user.balance)),
        account_number=c_nums["account_num"], 
        routing_number=c_nums["routing_num"],
        account_num_stars=c_nums["account_num_stars"],
        routing_num_stars=c_nums["routing_num_stars"],
        account=account,
        account_transactions=account_transactions
    )

@views.route("/signout")
@login_required
def signout():
    logout_user()
    flash("You have been logged out", category="success")
    return redirect(url_for('views.index'))

@views.route("/info/tos/")
def tos():
    md = markdown_path("core/md/tos.md")
    return render_template("info/tos.html", md=md, settings=settings, user=current_user)

@views.route("/info/privacy/")
def privacy():
    md = markdown_path("core/md/privacy.md")
    return render_template("info/privacy.html", md=md, settings=settings, user=current_user)

@views.app_errorhandler(403)
def error_403(e):
    return render_template("40x/403.html", settings=settings, user=current_user)

@views.app_errorhandler(404)
def error_404(e):
    return render_template("40x/404.html", settings=settings, user=current_user)

core/templates/profile/account.html
{% extends "base.html" %}
{% block title %}{{ user.name }}'s bank{% endblock %}
{% block main %}
	{% if overlay %}
		<div class="overlay"></div>
   	{% endif %}


	<h1>Welcome back, {{ user.name }}!</h1>
	{% include "include/profile-top.html" %}
	{% include "include/zombo.html" %}
	<div class="user-pages">
		<div class="user-page user-page-1">
			<div class="box user-page-box-left select-account-area">
				<h2>Transaction History for {{ account.name }}</h2>

				<div class="account" style="border: 0px; padding-left: 0px">
					<p style="font-weight: bold; text-align: center">Date</p>
					<p style="font-weight: bold; text-align: center">Name</p>
					<p style="font-weight: bold; text-align: center">Type</p>
					<p style="font-weight: bold; text-align: center">Amount</p>
				</div>
				{% if account_transactions %}
					{% for i in account_transactions %}
						<div class="account">
							<p class="text-align: left">{{ i.created.strftime("%b %e, %Y %I:%M%p") }}</p>
							<p class="text-align: left">{{ i.name }}</p>
							<p class="text-align: left">{{ i.transaction_type }}</p>
							<p class="text-align: left">${{ i.amount }}</p>
						</div>
					{% endfor %}
				{% else %}
					<p>This account has no transactions</p>
				{% endif %}
			</div>
		</div>

		<div class="user-page user-page-2">
			<div class="box user-page-box-right">
				<h2>Recent Transactions</h2>
				<h2>Announcements</h2>
				<div class="announcements">
					<p class="announcement"><span class="date"><b>Jul 19, 2022 10:36PM:</b> </span>Attention! Our executive branch is closing down soon, you may be eligible for a refund.</p>
					<p class="announcement"><span class="date"><b>Apr 20, 2022 3:50AM:</b> </span>Check out our new Tinder competitor, Hook-up-dog! You can swipe up on those you like and down on those you don't. Wanna hook up? Not much, how about you?</p>
					<p class="announcement"><span class="date"><b>Sep 21, 2021 9:05PM:</b> </span> Have you been sent too much money? Updog bank can now easily refund it to you.</p>
				</div>

				<img src="" id="advertisement" width="256" height="256">
				<div><small>Advertisement</small></div>

				<h2>What Does the Fox Say?</h2>
				<p class="announcement" id="fact"></p>

				<h2>Account Settings</h2>
				<a href="{{ url_for('views.signout') }}" rel="noopener noreferrer"><button class="header-button-outline">Sign Out <i class="fa fa-chevron-circle-right" aria-hidden="true"></i></button></a>
			</div>
		</div>
	</div>
    
	<!-- Cookies popup -->
	<div class="cookie-popup-frame">
		<div class="cookie-popup">
			<img src="{{ url_for('static', filename='img/cookie.svg') }}" alt="cookie image" width="90" height="90">

			<div class="cookie-data-area">
				<div class="cookies-1">
					<div>
						<h1>Attention!</h1>
						<div class="cookie-message">Updog Bank provides cookies in order to give you the best user experience possible. Do you consent?</div>
					</div>
		
					<div class="buttons">
						<button class="header-button cookies-yes">Yes</button>
						<button class="header-button-outline cookies-no">No</button>
					</div>
				</div>

				<div class="cookies-2">
					<h1>Attention!</h1>
					<div class="cookie-message">Okay, please provide a location for us to mail the cookies to:</div>
		
					<input type="text" placeholder="Address" maxlength="200" />
					<button class="header-button cookies-recieve">Recieve Cookies</button>
				</div>

				<div class="cookies-3">
					<h1>Attention!</h1>
					<div class="cookie-message">Your cookies will be sent to you in 1-2 business days.</div>
					<button class="header-button cookies-no">ok</button>
				</div>
			</div>
		</div>
	</div>


{% endblock %}
{% block specificjs %}
    <script src="{{ url_for('static', filename='js/jquery-3.6.0.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/clippy.js') }}"></script>
    <script src="{{ url_for('static', filename='js/profile.js') }}"></script>
	
	{% if settings.randomRefresh %}
		<script src="{{ url_for('static', filename='js/profile_refresh.js') }}"></script>
	{% endif %}
{% endblock  %}

core/templates/profile/select_account.html
{% extends "base.html" %}
{% block title %}Select Account{% endblock %}
{% block main %}
    {% if settings.fakeOverlay %}
        <div class="overlay"></div>
    {% endif %}
    
    {% include "include/zombo.html" %}
    {% if settings.quickSignOut %}
        <div class="hideSignOut">
            <div class="signOutPopup">
                <div class="signOutPopupContent">
                    <h1 class="slogan">Attention!</h1>
                    <p class="subtitle">We have detected sus activity on your account. For your safety, we have signed you out. Please log back in.</p>
        
                    <a href="{{ url_for('views.signout') }}" rel="noopener noreferrer">Return to homepage</a>
                </div>
            </div>
        </div>
    {% endif %}
    
    <h1>Welcome back, {{ user.name }}!</h1>
    {% include "include/profile-top.html" %}
    <div class="user-pages">
        <div class="user-page user-page-1">
            <div class="box user-page-box-left select-account-area">
                <h2>Please select an account</h2>
                {% if user.account %}
                    {% for i in user.account %}
                        <div class="account">
                            <a href="{{ url_for('views.account', uid=i.uid) }}" rel="noopener noreferrer">{{ i.name }}</a>
                            <p>${{ i.balance }}</p>
                        </div>
                    {% endfor %}
                {% else %}
                    <p>You have no accounts</p>
                {% endif %}
            </div>
        </div>

        <div class="user-page user-page-2">
            <div class="box user-page-box-right">
                <h2>Recent Transactions</h2>
                <h2>Announcements</h2>
                <div class="announcements">
                    <p class="announcement"><span class="date"><b>Jul 19, 2022 10:36PM:</b> </span>Attention! Our executive branch is closing down soon, you may be eligible for a refund.</p>
                    <p class="announcement"><span class="date"><b>Apr 20, 2022 3:50AM:</b> </span>Check out our new Tinder competitor, Hook-up-dog! You can swipe up on those you like and down on those you don't. Wanna hook up? Not much, how about you?</p>
                    <p class="announcement"><span class="date"><b>Sep 21, 2021 9:05PM:</b> </span> Have you been sent too much money? Updog bank can now easily refund it to you.</p>
                </div>

                <img src="" id="advertisement" width="256" height="256">
                <div><small>Advertisement</small></div>

                <h2>What Does the Fox Say?</h2>
                <p class="announcement" id="fact"></p>

                <h2>Account Settings</h2>
                <a href="{{ url_for('views.signout') }}" rel="noopener noreferrer"><button class="header-button-outline">Sign Out <i class="fa fa-chevron-circle-right" aria-hidden="true"></i></button></a>
            </div>
            
        </div>
    </div>
{% endblock %}
{% block specificjs %}
    <script src="{{ url_for('static', filename='js/jquery-3.6.0.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/clippy.js') }}"></script>
    <script src="{{ url_for('static', filename='js/profile.js') }}"></script>
    {% if settings.quickSignOut %}
        <script src="{{ url_for('static', filename='js/profile_quickSignOut.js') }}"></script>
    {% endif %}

    {% if settings.randomRefresh %}
        <script src="{{ url_for('static', filename='js/profile_refresh.js') }}"></script>
    {% endif %}
{% endblock  %}