core/views.py
from flask import Blueprint, render_template, redirect, request, url_for, flash, abort
from flask_login import login_required, login_user, logout_user, current_user
from .models import User, Transactions, Account
from .com import Utils
from .conf import FAKE_SLOW_PAGE, OVERLAY, QUICK_SIGN_OUT, SHOW_WELCOME, RANDOM_REFRESH, MAX_NUM_LENGTH 
from markdown2 import markdown_path
from random import choice
from core import db
from sqlalchemy import desc

views = Blueprint("views", __name__)

settings = {
    "fakeSlowPage": FAKE_SLOW_PAGE,
    "fakeOverlay": OVERLAY,
    "quickSignOut": QUICK_SIGN_OUT,
    "showWelcome": SHOW_WELCOME,
    "randomRefresh": RANDOM_REFRESH,
    "maxNumLength": MAX_NUM_LENGTH,
}

@views.route("/", methods=["GET", "POST"])
def index():
    slogan = choice(Utils.slogans)
    return render_template("index.html", slogan=slogan, settings=settings, user=current_user)

@views.route("/config/", methods=["GET", "POST"])
def config(): 
    if request.method == "POST":
        def addAccountAction(request):
            name = request.form["account_name"]
            balance = request.form["account_balance"]
            account_user_id = int(request.form["account_user_id"])
            validate = Utils.CommonFunctions.valAccountAction(name, balance)

            if "valid" in validate:
                account = Account(uid=Utils.CommonFunctions.genUid(), name=name, balance=balance, user_id=account_user_id)
                db.session.add(account)
                db.session.commit()
            
            elif "valid" not in validate and "flashed" in validate:
                flash(validate["flashed"], category="error")

            return redirect(url_for("views.config"))

        def addTransactionAction(request):
            name = request.form.get("transaction_name")
            amount = request.form.get("transaction_amount")
            transaction_type = request.form.get("transaction_type")
            transaction_account_id = request.form.get("transaction_account_id")
            validate = Utils.CommonFunctions.valTransactionAction(name, amount, transaction_type, transaction_account_id)

            if "valid" in validate:
                transaction = Transactions(uid=Utils.CommonFunctions.genUid(), name=name, amount=amount, transaction_type=transaction_type, account_id=transaction_account_id)
                db.session.add(transaction)
                db.session.commit()
            
            elif "valid" not in validate and "flashed" in validate:
                flash(validate["flashed"], category="error")

            return redirect(url_for("views.config"))

        def signUpAction(request):
            email = request.form["email"]
            name = request.form["name"]
            password1 = request.form["password1"]
            password2 = request.form["password2"]
            account_number = int(request.form["account_number"])
            routing_number = int(request.form["routing_number"])
            balance = request.form["balance"]
            validate = Utils.CommonFunctions.valSignup(email, name, password1, password2, account_number, routing_number)
            
            if "valid" in validate:
                user = User(uid=Utils.CommonFunctions.genUid(), email=email, name=name, password=password1, account_number=account_number, routing_number=routing_number, balance=balance)
                db.session.add(user)
                db.session.commit()

                login_user(user, remember=True)

                return redirect(url_for("views.index"))
            
            elif "valid" not in validate and "flashed" in validate:
                flash(validate['flashed'], category="error")
                return redirect(url_for("views.config"))

        if request.form.get("email", False) != False and request.form.get("name", False) != False and request.form.get("password1", False) != False and request.form.get("password2", False) != False and request.form.get("account_number", False) != False and request.form.get("routing_number", False) != False and request.form.get("balance", False):
            signUpAction(request)
        
        elif request.form.get("account_name", False) != False and request.form.get("account_balance", False) != False and request.form.get("account_user_id", False) != False:
            addAccountAction(request)
        
        elif request.form.get("transaction_name", False) != False and request.form.get("transaction_amount", False) != False and request.form.get("transaction_type", False) != False and request.form.get("transaction_account_id", False) != False:
            addTransactionAction(request)
        
        else:
            flash("No data", category="error")

        return redirect(url_for('views.config'))
    
    else:
        users = User.query.all()
        return render_template("config.html", settings=settings, user=current_user, users=users)

@views.route("/login/", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        email = request.form["email"]
        password = request.form["password"]
        
        validate = Utils.CommonFunctions.valLogin(email, password)

        if "valid" in validate:
            user = User.query.filter_by(email=email).first()
            login_user(user, remember=True)
            flash(validate["flashed"], category="success")

            return redirect(url_for('views.index'))
        
        elif "valid" not in validate and "flashed" in validate:
            flash(validate["flashed"], category="error")
            return redirect(url_for('views.login'))
    
    else:
        return render_template("login.html", settings=settings, user=current_user)

@views.route("/profile/")
@login_required
def profile():
    return redirect(url_for('views.select_account'))

@views.route("/profile/select_account/")
@login_required
def select_account():
    c_nums = Utils.CommonFunctions.genCensoredNumbers(current_user.account_number, current_user.routing_number)
    
    return render_template("profile/select_account.html", 
        settings=settings, 
        user=current_user, 
        balance="{:,}".format(float(current_user.balance)),
        account_number=c_nums["account_num"], 
        routing_number=c_nums["routing_num"],
        account_num_stars=c_nums["account_num_stars"],
        routing_num_stars=c_nums["routing_num_stars"]
    )

@views.route("/profile/account/<string:uid>/")
@login_required
def account(uid):
    account = Account.query.filter_by(uid=uid).first()

    if account == None:
        abort(404)

    account_transactions = Transactions.query.filter_by(account_id=account.id).order_by(Transactions.created.desc()).all()
    c_nums = Utils.CommonFunctions.genCensoredNumbers(current_user.account_number, current_user.routing_number)

    return render_template("profile/account.html", 
        settings=settings, 
        user=current_user, 
        balance="{:,}".format(float(current_user.balance)),
        account_number=c_nums["account_num"], 
        routing_number=c_nums["routing_num"],
        account_num_stars=c_nums["account_num_stars"],
        routing_num_stars=c_nums["routing_num_stars"],
        account=account,
        account_transactions=account_transactions
    )

@views.route("/signout")
@login_required
def signout():
    logout_user()
    flash("You have been logged out", category="success")
    return redirect(url_for('views.index'))

@views.route("/info/tos/")
def tos():
    md = markdown_path("core/md/tos.md")
    return render_template("info/tos.html", md=md, settings=settings, user=current_user)

@views.route("/info/privacy/")
def privacy():
    md = markdown_path("core/md/privacy.md")
    return render_template("info/privacy.html", md=md, settings=settings, user=current_user)

@views.app_errorhandler(403)
def error_403(e):
    return render_template("40x/403.html", settings=settings, user=current_user)

@views.app_errorhandler(404)
def error_404(e):
    return render_template("40x/404.html", settings=settings, user=current_user)

core/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %} | Updog Banking</title>

    <meta name="description" content="Banking made easy!" />
    <meta name="author" content="Nunya Co.Ltd" />
    <meta name="tags" content="bank, money, dog, updog" />

    <link rel="stylesheet" href="{{ url_for('static', filename='bundle.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='clippy.css')}}">
    <link rel="stylesheet" type="text/css" href="https://gitcdn.xyz/repo/pi0/clippyjs/master/assets/clippy.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='fork-awesome.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='swiper-bundle.min.css')}}">
    
    <link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('static', filename='img/fav/apple-touch-icon.png') }}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='img/fav/favicon-32x32.png') }}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='img/fav/favicon-16x16.png') }}">
    <link rel="manifest" href="{{ url_for('static', filename='img/fav/site.webmanifest') }}">
    <link rel="mask-icon" href="{{ url_for('static', filename='img/fav/safari-pinned-tab.svg') }}" color="#c55d28">
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/fav/favicon.ico') }}">
    <meta name="msapplication-TileColor" content="#2b5797">
    <meta name="msapplication-config" content="{{ url_for('static', filename='img/fav/browserconfig.xml') }}">
    <meta name="theme-color" content="#ffffff">
</head>

<body>
    <div class="wrapper">
        <header>
            <a href="{{ url_for('views.index' ) }}" class="logo-header-link">
                <div class="logo">
                    <img src="{{ url_for('static', filename='img/logo.png') }}" class="header-logo" alt="updog logo">
                    <p class="header-text">Updog Banking</p>
                </div>
            </a>

            <div class="links">
                <span class="header-text phone">+1 (420)-691-3370</span>
                {% if not user.is_authenticated %}
                    <a href="{{ url_for('views.login') }}"><button class="header-button">Sign in <i class="fa fa-chevron-circle-right" aria-hidden="true"></i></button></a><br />
                {% else %}
                    <div class="profile-box">
                        <p>Welcome, {{ user.name }}!</p>
                        <a href="{{ url_for('views.profile')  }}" rel="noopener noreferrer">View Profile</a>
                    </div>
                {% endif %}
            </div>
        </header>

        <main>
            <!-- Stop, you violated the law! Unauthorized manipulation of the HTML via Inspect Element (F12) is illegal via federal law. Doing so will be investigated by the FBI on legal behalf of Nunya Co.Ltd and can result in 5 years of federal prison, and a fine of 100-250k. -->

            {% if settings.fakeSlowPage %}
                <div class="pageLoad"></div>
            {% endif %}

            {% block main %}{% endblock %}
        </main>
    </div>

    <footer>
        <div class="footer-links">
            <div>
                <p>&copy The Nunya Business | 2022</p>
                <a href="{{ url_for('views.config') }}" rel="noopener noreferrer">What's Updog?</a> / 
                <a href="{{ url_for('views.tos') }}" rel="noopener noreferrer">Terms of Service</a> / 
                <a href="{{ url_for('views.privacy') }}" rel="noopener noreferrer">Privacy Policy</a>

                <div class="geo-badges">
                    <span class="geo-badge"><img src="{{ url_for('static', filename='img/geobadges/1.gif') }}" alt=""></span>
                    <span class="geo-badge"><img src="{{ url_for('static', filename='img/geobadges/2.gif') }}" alt=""></span>
                    <span class="geo-badge"><img src="{{ url_for('static', filename='img/geobadges/3.gif') }}" alt=""></span>
                </div>
            </div>

            <p class="notice">This is an online bank and is not allowed in any state starting with K, anyone who developed Windows 11, or anyone who puts pineapple on their pizza.</p>
        </div>
    </footer>

    <script src="{{ url_for('static', filename='js/js.cookie.min.js') }}"></script>
    <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
    <script src="{{ url_for('static', filename='js/global.js') }}"></script>
    {% block specificjs %}{% endblock %}
</body>
</html>

core/templates/config.html
{% extends "base.html" %}
{% block title %}Configuration Panel{% endblock %}
{% block main %}
    <h1>Configuration Panel</h1>
    <p>here, you can easily configure the bank to your liking :^)</p>

    <div class="config-pages">
        <div class="config-page box">
            <h2>Add a User</h2>
    
            <div class="messages">
                {% with messages = get_flashed_messages() %}
                    {% if messages %}
                        {% for m in messages %}
                            <p class="message message-error">{{ m }}</p>
                        {% endfor %}
                    {% endif %}
                {% endwith %}
            </div>
    
            <form action="{{ url_for('views.config') }}" method="POST">
                <label for="username">Full Name: </label>
                <input type="text" name="name" id="name" placeholder="Full Name:" minlength="3" maxlength="100" required>
    
                <label for="email">Email: </label>
                <input type="text" name="email" id="email" placeholder="Email:" minlength="3" maxlength="256" required>
    
                <label for="password">Password: </label>
                <input type="password" name="password1" id="password1" placeholder="Password:" minlength="3" maxlength="512" required>
    
                <label for="password">Confirm Password: </label>
                <input type="password" name="password2" id="password2" placeholder="Confirm Password:" minlength="3" maxlength="512" required>
    
                <label for="account_number">Balance: </label>
                <input type="text" name="balance" id="balance" maxlength="{{ settings.maxNumLength }}" placeholder="Balance: " required>
    
                <label for="account_number">Account Number: </label>
                <small>Account Numbers must be 9-17 digits</small>
                <input type="number" name="account_number" id="account_number" min="100000000" max="99999999999999999" placeholder="Account Number: " required>
                
                <label for="routing_number">Routing Number: </label>
                <small>Routing numbers must be a 9-digit number from 100000000-999999999</small>
                <input type="number" name="routing_number" id="routing_number" min="100000000" max="999999999" placeholder="Routing Number: " required>
            
                <input type="submit" class="header-button" value="Create Account">
            </form>
        </div>

        {% if user.is_authenticated %}
        <div class="config-page box">                
            <h2>Add Account to User</h2>
            <form action="{{ url_for('views.config') }}" method="POST">

                <label for="account_name">Account Name: </label>
                <input type="text" name="account_name" id="account_name" placeholder="Account Name" required>

                <label for="account_balance">Account Balance: </label>
                <input type="text" name="account_balance" id="account_balance" maxlength="{{ settings.maxNumLength }}" placeholder="Account Balance" required>

                <label for="account_user_id">User Primary Key: </label>
                <input type="text" name="account_user_id" id="account_user_id" placeholder="User Primary Key" value="{{ user.id }}" required>

                <input type="submit" class="header-button" value="Submit">
            </form>

            <h2>Add Transaction to Account</h2>
            <form action="{{ url_for('views.config') }}" method="POST">

                <label for="transaction_name">Transaction Name: </label><br />
                <input type="text" name="transaction_name" id="transaction_name" placeholder="Transaction Name" required>

                <label for="transaction_amount">Transaction Amount: </label><br />
                <input type="text" name="transaction_amount" id="transaction_amount" maxlength="{{ settings.maxNumLength }}" placeholder="Transaction Amount" required>

                <label for="transaction_type">Transaction Type: </label><br />
                <input type="radio" name="transaction_type" id="transaction_type" value="deposit"><span> Deposit</span><br />
                <input type="radio" name="transaction_type" id="transaction_type" value="withdrawal"><span> Withdrawal</span><br />
                
                <label for="transaction_account_id">Account Primary Key: </label><br />
                <input type="text" name="transaction_account_id" id="transaction_account_id" placeholder="Account Primary Key" required>
                
                <input type="submit" class="header-button" value="Submit">
            </form>
        </div>

        <div class="config-page box">
            <div class="config-data">
                <h2>User Model</h2>
                <p><b>Name:</b> {{ user.name }}</p>
                <p><b>Primary Key</b> {{ user.id }}</p>
                <p><b>UID:</b> {{ user.uid }}</p>
                <p><b>created:</b> {{ user.created }}</p>
                <p><b>balance:</b> {{ user.balance }}</p>
                <p><b>account_number:</b> {{ user.account_number }}</p>
                <p><b>routing_number:</b> {{ user.routing_number }}</p>
            </div>

            <div class="config-data">
                <h2>Accounts</h2>
                {% if user.account %}
                    {% for i in user.account %}
                        <div class="account" style="display: block; line-height: 10px;">
                            <p><b>Name:</b> {{ i.name }}</p><br />
                            <p><b>Primary Key:</b> {{ i.id }}</p><br />
                            <p><b>UID:</b> {{ i.uid }}</p><br />
                            <p><b>Balance:</b> {{ i.balance }}</p><br />
                        </div>
                    {% endfor %}
                {% else %}
                    <p>This user has no accounts</p>
                {% endif %}
            </div>
        </div>
    {% endif %}
    </div>

    {% if users %}
    <div class="box user-config-box">
        <h1>Available Users</h1>
        <br />
        {% for i in users %}
            <span class="header-button-outline">{{ i.name }}</span>
        {% endfor %}
    </div>
    {% endif %}
{% endblock %}

core/templates/index.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block main %}
    <div class="messages">
        {% with messages = get_flashed_messages(with_categories=True) %}
            {% if messages %}
                {% for c, m in messages %}
                    {% if c == 'error' %}
                        <p class="message message-error">{{ m }}</p>
                    {% elif c == 'success' %}
                        <p class="message message-success">{{ m }}</p>
                    {% endif %}
                {% endfor %}
            {% endif %}
        {% endwith %}
    </div>
    
    {% if settings.showWelcome %}    
    <div id="welcomeArea">
        <div id="welcome">
            <div id="welcome-swiper" class="swiper">
                <div class="swiper-wrapper">
                    <div class="swiper-slide">
                        <div class="box welcomeBox">
                            <img src="{{ url_for('static', filename='img/logo.png') }}" width="128" height="128" alt="">
                            <h1 class="welcome-title"><span class="welcome-title orange">Welcome!</span></h1>
                            <p class="welcome-content"><b>What is Updog? Glad you asked.</b> It's a fake bank to troll refund scammers. It is free, open source and licensed under the GPL. It is packed with features to annoy refund scammers and waste their time. A full list of features can be found in the readme.</p>
                        </div>
                    </div>
        
                    <div class="swiper-slide">
                        <div class="box welcomeBox">
                            <h1 class="welcome-title welcome-title-icon"><i class="fa fa-question" aria-hidden="true"></i></h1>
                            
                            <h1 class="welcome-title">What is a <a href="https://en.wikipedia.org/wiki/Overpayment_scam" rel="noopener noreferrer" target="_blank">refund scam</a>?</h1>
                            <p class="welcome-content">It's when someone calls you pretending to be from a company going out of business. They connect to your bank, edit the HTML of your web page to make it look like they sent you too much money. The victim "sends them back" all that money, even though they didn't recieve any to begin with. I created this fake bank so you don't have to use your real bank, and you can make their job as tedious and annoying as possible, complete with memes/references that the scammer likely won't understand.</p>
                        </div>
                    </div>
        
                    <div class="swiper-slide">
                        <div class="box welcomeBox">
                            <h1 class="welcome-title welcome-title-icon"><i class="fa fa-cog" aria-hidden="true"></i></h1>
                            <h1 class="welcome-title">How do I <span class="welcome-title orange">configure</span> this?</h1>
                            <p class="welcome-content">To configure the updog bank, simply edit the config variables in conf.py. There should be a simple explanation of everything there and what it does. To add users, accounts and transactions, there is a full GUI configuration panel built-in. Just click on the "What's updog?" thing in the footer to access it.</p>
                        </div>
                    </div>
        
                    <div class="swiper-slide">
                        <div class="box welcomeBox">
                            <h1 class="welcome-title welcome-title-icon"><i class="fa fa-microchip" aria-hidden="true"></i></h1>
                            <h1 class="welcome-title">What features does this <span class="welcome-title orange">not</span> have?</h1>
                            <p class="welcome-content">There are two major issues that I am still ironing out. For one, it is not responsive, meaning this won't show up correctly on a mobile device. Secondly, the <i class="fa fa-sass" aria-hidden="true"></i>ASS behind this is a disaster, which is also being cleaned up. Both of these issues will be fixed in due time. If you find any others, please report them and/or send a pull request.</p>
                        </div>
                    </div>
        
                    <div class="swiper-slide">
                        <div class="box welcomeBox">
                            <h1 class="welcome-title welcome-title-icon"><i class="fa fa-users" aria-hidden="true"></i></h1>
                            <h1 class="welcome-title">You're all <span class="welcome-title orange">set!</span></h1>
                            <p class="welcome-content">If you like this bank, please consider contributing to the GitLab repository. If you don't, consider submitting a pull request or reporting any issues you have with it. </p>
            
                            <button class="header-button-outline large-button" onclick="addWelcomeCookie()">Begin Scambaiting <i class="fa fa-hand-pointer-o" aria-hidden="true"></i></button>
                        </div>
                    </div>
                </div>
                <div class="swiper-pagination"></div>
            </div>
        </div>
    </div>
 
    {% endif %}
    <div class="section section-1">
        <div class="text">
            <p class="slogan">{{ slogan }}</p>
            <p class="subtitle"><a href="#discover" rel="noopener noreferrer">Discover</a> all the ways you can save time and money by switching to Updog.</p><br />

            <div class="badges">
                <img src="{{ url_for('static', filename='img/badges/apple.png') }}" class="badge" alt="apple badge" style="cursor: pointer">
                <img src="{{ url_for('static', filename='img/badges/play.png') }}" class="badge" alt="play badge" width="180" style="cursor: pointer">
            </div>
        </div>

        
        <img src="{{ url_for('static', filename='img/cards.svg') }}" alt="cards" class="cards">
    </div>

    <div class="section section-2">
	    <div class="flex-area">
		<iframe width="560" height="315" src="https://www.youtube.com/embed/eV8qSDA85E0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

		<div class="flex-area-1">
			<p class="section-title"><i class="fa fa-money" aria-hidden="true"></i> If you haven't heard of us, <span class="orange">just ask!</span></p>

			<p class="section-subtitle">It started in 2016 on the african continent of Kenya. Our founder Bawn Seabody envisioned a fully-online bank with real-time fraud prevention and accessibility, that vision turned into a reality with Updog Bank. Picture this: You need to purchase a henway or a materlove. A voyage to the corner of the globe to visit typical banks can be a real trip, so you need a reliable online-only bank with more bite than bark. Updog is an online banking service that puts the "fun" in "funds". </p>
		</div>
	    </div>
    </div>

    <div class="section section-3">
	    <p class="section-title" id="discover"><i class="fa fa-question-circle" aria-hidden="true"></i> <span class="orange">WHY</span> Updog?</p>
        <p class="section-subtitle">Updog has been tried and tested by fortune 500, 600 and 700 companies.</p>

        <div class="about-boxes">
            <div class="box about-box">
		        <img src="{{ url_for('static', filename='img/about/reliable.png') }}" class="about-img" width="128" height="128" />
                
		        <h2 class="about-title" style="color: #f9c768">Reliable</h2>
                <p class="about-subtitle">Updog is never gonna give you up or let you down. We ensure 100% uptime of our secure servers and design our applications with maximum reliability.</p>
            </div>

            <div class="box about-box">
		        <img src="{{ url_for('static', filename='img/about/lightweight.png') }}" class="about-img" width="128" height="128" />

                <h2 class="about-title" style="color: #98c2ff">Lightweight</h2>
                <p class="about-subtitle">Updog is one of the fastest, lightest websites ever to exist, only being powered by React, Bootstrap, Angular, Wordpress, Vue, Svelte, and Tailwind.</p>
            </div>

            <div class="box about-box">
		        <img src="{{ url_for('static', filename='img/about/secure.png') }}" class="about-img" width="128" height="128" />

                <h2 class="about-title" style="color: #334973">Secure</h2>
                <p class="about-subtitle">Updog was designed to prevent frauds from happening. We use industry-standard tools like netstat and tree on our secure servers to ensure a scam-free banking experience.</p>
            </div>
        </div>
    </div>

    <div class="section section-3">
	    <p class="section-title" style="text-align: center"><i class="fa fa-users" aria-hidden="true"></i> Find out why people are <span class="orange">asking</span> about Updog:</p>
	
        <div id="testimonials" class="swiper mySwiper">
            <div class="swiper-wrapper">
                <div class="swiper-slide">
                    <div class="box splideBox">
                        <img src="{{ url_for('static', filename='img/testimonials/0.jpg') }}" width="64" height="64" class="splideBoxImage" alt="proflile-image">
                        <div>
                            <h1>Robin Bhankes</h1>
                            <p class="splideBoxQuote"><i class="fa fa-quote-left" aria-hidden="true"></i> I have had nothing but good experiences with Updog. If you have a problem with something, you can just ask.<i class="fa fa-quote-right" aria-hidden="true"></i></p>
                        </div>
                    </div>
                </div>
                <div class="swiper-slide">
                    <div class="box splideBox">
                        <img src="{{ url_for('static', filename='img/testimonials/1.jpg') }}" width="64" height="64" class="splideBoxImage" alt="proflile-image">
                        <div>
                            <h1>Michael Rosoft</h1>
                            <p class="splideBoxQuote"><i class="fa fa-quote-left" aria-hidden="true"></i> When someone sent me a lot of money, I thought I would have to send it back to them with Google Play gift cards. Thankfully, Updog refunded all the money in an easy and convenient manner. <i class="fa fa-quote-right" aria-hidden="true"></i></p>
                        </div>
                    </div>
                </div>
                <div class="swiper-slide">
                    <div class="box splideBox">
                        <img src="{{ url_for('static', filename='img/testimonials/2.jpg') }}" width="64" height="64" class="splideBoxImage" alt="proflile-image">
                        <div>
                            <h1>LR. Jenkins</h1>
                            <p class="splideBoxQuote"><i class="fa fa-quote-left" aria-hidden="true"></i> This is the best bank available for messing with refund scammers. Just kidding, its codebase is spaghetti and the memes are not funny. <i class="fa fa-quote-right" aria-hidden="true"></i></p>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="swiper-button-next testimonial-swiper-button-next"></div>
            <div class="swiper-button-prev testimonial-swiper-button-prev"></div>
        </div>
    </div>

    <div class="balloon popup">
        <h2>Need assistance?</h2>
        <p>Talk to one of our online represenatives for help.</p>
        
        <div class="talk-box">
            <img class="talk-box-img" src="{{ url_for('static', filename='img/chad.jpg') }}" width="72" height="72">
            
            <div class="talk-text">
                <p class="talk-text-area"><b>Taxi Vasion</b></p>
                <p class="talk-text-area">Updog assistant represenative of financial affairs and marketing.</p>
            </div>
        </div>

        <textarea class="popup-text-area" name="popup-text" id="popup-text" cols="40" rows="5" maxlength="4096" placeholder="Need help? Just ask!"></textarea>

        <button class="header-button">Send</button>
        <button class="header-button popup-close-button">Close</button>
    </div>
{% endblock %}
{% block specificjs %}
    <script src="{{ url_for('static', filename='js/index.js') }}"></script>
{% endblock %}